"""create user table

Revision ID: 3c4a4b9a24aa
Revises: 
Create Date: 2025-07-29 14:34:19.356455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4a4b9a24aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('user_is_active', sa.Boolean(), nullable=False),
    sa.Column('user_is_verified', sa.Boolean(), nullable=False),
    sa.Column('user_service_role', sa.Enum('ADMIN', 'USER', name='service_role_enum', native_enum=False), nullable=False),
    sa.Column('user_create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_email'), 'user', ['user_email'], unique=True)
    op.create_index(op.f('ix_user_user_username'), 'user', ['user_username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
